"use client"

import { GlowCard } from "@/components/common/glow-card"
import { Button } from "@/components/ui/button"
import { Calendar, Clock, Users, Zap, Check, X } from "lucide-react"
import { useState } from "react"

interface EventProposalCardProps {
  title: string
  date: string
  time: string
  duration: string
  participants: string[]
  canApprove?: boolean
  status?: "pending" | "approved" | "rejected"
}

export function EventProposalCard({
  title,
  date,
  time,
  duration,
  participants,
  canApprove = false,
  status = "pending",
}: EventProposalCardProps) {
  const [isApproving, setIsApproving] = useState(false)
  const [localStatus, setLocalStatus] = useState(status)

  const handleApprove = async () => {
    setIsApproving(true)
    await new Promise((resolve) => setTimeout(resolve, 1000))
    setLocalStatus("approved")
    setIsApproving(false)
  }

  const handleReject = async () => {
    setIsApproving(true)
    await new Promise((resolve) => setTimeout(resolve, 500))
    setLocalStatus("rejected")
    setIsApproving(false)
  }

  return (
    <GlowCard className="p-6">
      <div className="flex items-center gap-2 mb-4">
        <div className="w-8 h-8 rounded-lg bg-accent/10 flex items-center justify-center">
          <Zap className="w-4 h-4 text-accent" />
        </div>
        <span className="text-xs font-mono text-cream/50">
          Generated by Coordination Engine
        </span>
      </div>

      <h3 className="text-lg font-semibold text-cream mb-4 font-[family-name:var(--font-display)]">
        {title}
      </h3>

      <div className="space-y-3 mb-6">
        <div className="flex items-center gap-3 text-sm">
          <Calendar className="w-4 h-4 text-accent" />
          <span className="text-cream">{date}</span>
        </div>
        <div className="flex items-center gap-3 text-sm">
          <Clock className="w-4 h-4 text-cream/50" />
          <span className="text-cream">
            {time} ({duration})
          </span>
        </div>
        <div className="flex items-center gap-3 text-sm">
          <Users className="w-4 h-4 text-emerald-500" />
          <div className="flex flex-wrap gap-1">
            {participants.map((p, i) => (
              <span key={i} className="text-accent">
                {p}
                {i < participants.length - 1 && (
                  <span className="text-cream/50">, </span>
                )}
              </span>
            ))}
          </div>
        </div>
      </div>

      {/* Google Calendar Preview */}
      <div className="bg-charcoal-light rounded-lg p-4 border border-charcoal-lighter mb-6">
        <div className="flex items-center gap-2 mb-2">
          <div className="w-3 h-3 rounded-sm bg-accent" />
          <span className="text-sm font-medium text-cream">{title}</span>
        </div>
        <p className="text-xs text-cream/50">
          {date} at {time}
        </p>
      </div>

      {/* Actions */}
      {canApprove && localStatus === "pending" && (
        <div className="flex gap-3">
          <Button
            onClick={handleApprove}
            disabled={isApproving}
            className="flex-1 bg-emerald-600 hover:bg-emerald-700 text-white"
          >
            {isApproving ? (
              <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
            ) : (
              <>
                <Check className="w-4 h-4 mr-2" />
                Approve
              </>
            )}
          </Button>
          <Button
            onClick={handleReject}
            disabled={isApproving}
            variant="outline"
            className="flex-1 border-red-500/30 text-red-500 hover:bg-red-500/10"
          >
            <X className="w-4 h-4 mr-2" />
            Reject
          </Button>
        </div>
      )}

      {localStatus === "approved" && (
        <div className="flex items-center justify-center gap-2 py-3 bg-emerald-500/10 rounded-lg border border-emerald-500/20">
          <Check className="w-5 h-5 text-emerald-500" />
          <span className="text-emerald-500 font-medium">Approved</span>
        </div>
      )}

      {localStatus === "rejected" && (
        <div className="flex items-center justify-center gap-2 py-3 bg-red-500/10 rounded-lg border border-red-500/20">
          <X className="w-5 h-5 text-red-500" />
          <span className="text-red-500 font-medium">Rejected</span>
        </div>
      )}
    </GlowCard>
  )
}
